jobs:
  automerge:
    runs-on: ubuntu-latest
  steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          LOG: TRACE
          MERGE_COMMIT_MESSAGE: pull-request-description
          MERGE_FORKS: "false"
          MERGE_LABELS: "automerge,!work in progress"
          MERGE_METHOD: squash
          MERGE_REMOVE_LABELS: automerge
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"
          UPDATE_LABELS: ""
          UPDATE_METHOD: rebase
true:
  check_suite:
    types:
      - completed
  pull_request:
      types:
        - labeled
        - unlabeled
        - synchronize
        - opened
        - edited
        - ready_for_review
        - reopened
        - unlocked
  pull_request_review:
    types:
      - submitted
  schedule:
    -
      cron: "10 06 * * 1"
  status: {}
