name: Merge Schedule
on:
  pull_request:
    types:
      - opened
      - edited
  schedule:
    - cron: 20 7 * * 4 
jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v1.3.0
        env:
          GITHUB_TOKEN: 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 
