name: Auto-Merge Pull Requests
on:
  # Add a cron to determine what time you want to auto-merge your pull request(s). Crons are written in UTC:
  # https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule.
  schedule:
    - cron: '25 04 16 08 1'

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-Merge Pull Requests
        uses: pascalgn/automerge-action@80acb0f883348dcfd0e526288f7d27a12b9333be
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: auto-merge
          MERGE_METHOD: squash
          MERGE_COMMIT_MESSAGE: automatic
          MERGE_FORKS: false
          MERGE_RETRIES: 6
          MERGE_RETRY_SLEEP: 10000
          UPDATE_LABELS: auto-merge
          UPDATE_METHOD: merge
