name: Merge Schedule
on:
  pull_request:
    types:
      - opened
      - edited
  schedule:
    - cron: 55 22 * * * 
jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v1.3.0
	with:
	  merge_method: squash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
